<a href="https://colab.research.google.com/github/sumitsaurabhss/ai-with-python/blob/main/LLMs_using_HuggingFace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
#!pip install huggingface_hub

In [3]:
from huggingface_hub import HfApi

In [4]:
api = HfApi()

#list(api.list_models())

In [5]:
models = api.list_models(
    task="text-classification",
    sort="downloads",
    direction=-1,
    limit=3
)

model_list = list(models)
print(model_list)

[ModelInfo(id='facebook/fasttext-language-identification', author=None, sha=None, created_at=datetime.datetime(2023, 3, 6, 12, 52, 50, tzinfo=datetime.timezone.utc), last_modified=None, private=False, gated=None, disabled=None, downloads=52727411, likes=162, library_name='fasttext', tags=['fasttext', 'text-classification', 'language-identification', 'arxiv:1607.04606', 'arxiv:1802.06893', 'arxiv:1607.01759', 'arxiv:1612.03651', 'license:cc-by-nc-4.0', 'region:us'], pipeline_tag='text-classification', mask_token=None, card_data=None, widget_data=None, model_index=None, config=None, transformers_info=None, siblings=None, spaces=None, safetensors=None), ModelInfo(id='tasksource/deberta-small-long-nli', author=None, sha=None, created_at=datetime.datetime(2024, 1, 31, 12, 2, 12, tzinfo=datetime.timezone.utc), last_modified=None, private=False, gated=None, disabled=None, downloads=8697272, likes=21, library_name='transformers', tags=['transformers', 'pytorch', 'safetensors', 'deberta-v2', 't

In [6]:
from transformers import AutoModel

In [7]:
modelId = "distilbert-base-uncased-finetuned-sst-2-english"

model = AutoModel.from_pretrained(modelId)

model.save_pretrained(save_directory=f'models/{modelId}')

In [8]:
#!pip install datasets

In [9]:
from datasets import load_dataset_builder

In [10]:
data_builder = load_dataset_builder('imdb')

In [11]:
print(data_builder.info.description)

In [12]:
print(data_builder.info.features)

{'text': Value(dtype='string', id=None), 'label': ClassLabel(names=['neg', 'pos'], id=None)}


In [13]:
from datasets import load_dataset

data = load_dataset('imdb')

In [14]:
data = load_dataset('imdb', split='train')

In [15]:
#data_wiki = load_dataset('wikipedia', '20220301.en')

In [16]:
filtered = data.filter(lambda row: row['label']==0)
print(filtered)

Dataset({
    features: ['text', 'label'],
    num_rows: 12500
})


In [17]:
print(filtered[0])

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

In [18]:
print(filtered[0]['text'])

I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, eve

In [19]:
filtered = data.filter(lambda row: 'politic' in row['text'])
print(filtered)

Dataset({
    features: ['text', 'label'],
    num_rows: 746
})


In [20]:
sliced = data.select(range(2))
print(sliced)

Dataset({
    features: ['text', 'label'],
    num_rows: 2
})


In [21]:
print(sliced[0])
print(sliced[1])

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far be

In [22]:
print(sliced[0]['text'])
print(sliced[1]['text'])

I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, eve

**From deeplearning.ai**

In [23]:
from transformers.utils import logging
logging.set_verbosity_error()

In [24]:
from transformers import pipeline

In [25]:
chatbot = pipeline("text2text-generation", model="facebook/blenderbot-400M-distill")

In [26]:
user_message = """
What are some fun activities to do in the winter?

"""

In [27]:
from transformers import Text2TextGenerationPipeline

In [28]:
#text2text = Text2TextGenerationPipeline(model='chatbot', task=user_message)
#print(text2text)

In [29]:
chatbot(user_message)

[{'generated_text': ' I love snowboarding and skiing.  Do you have any winter activities you like to do?'}]

In [30]:
import gc

In [31]:
del chatbot

In [32]:
gc.collect()

8

In [33]:
import torch

In [34]:
translator = pipeline(task="translation",
                      model="facebook/nllb-200-distilled-600M",
                      torch_dtype=torch.bfloat16)

In [35]:
text = """\
My puppy is adorable, \
Your kitten is cute.
Her panda is friendly.
His llama is thoughtful. \
We all have nice pets!"""

In [36]:
text_translated = translator(text,
                             src_lang="eng_Latn",
                             tgt_lang="urd_Arab")

print(text_translated)

[{'translation_text': 'میرا کتا بہت پیارا ہے، آپ کا بلی کا بچہ بہت پیارا ہے اس کا پانڈا بہت دوستانہ ہے اس کا لاما بہت پرجوش ہے ہم سب کے پاس اچھے پالتو جانور ہیں'}]


In [37]:
del translator

In [38]:
gc.collect()

0

In [39]:
summarizer = pipeline(task="summarization",
                      model="facebook/bart-large-cnn",
                      torch_dtype=torch.bfloat16)

In [40]:
text = """Paris is the capital and most populous city of France, with
          an estimated population of 2,175,601 residents as of 2018,
          in an area of more than 105 square kilometres (41 square
          miles). The City of Paris is the centre and seat of
          government of the region and province of Île-de-France, or
          Paris Region, which has an estimated population of
          12,174,880, or about 18 percent of the population of France
          as of 2017."""

In [41]:
summary = summarizer(text,
                     min_length=10,
                     max_length=100)

In [42]:
summary

[{'summary_text': 'Paris is the capital and most populous city of France, with an estimated population of 2,175,601 residents as of 2018. The City of Paris is the centre and seat of the government of the region and province of Île-de-France.'}]

In [43]:
del summarizer

In [44]:
gc.collect()

0

In [45]:
#!pip install sentence-transformers

In [46]:
from sentence_transformers import SentenceTransformer

In [47]:
model = SentenceTransformer('all-MiniLM-L6-v2')

In [48]:
sentences1 = ['The cat sits outside',
              'A man is playing guitar',
              'The movies are awesome']

In [49]:
embeddings1 = model.encode(sentences1, convert_to_tensor=True)
print(embeddings1)

tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])


In [50]:
sentences2 = ['The dog plays in the garden',
              'A woman watches TV',
              'The new movie is so great']

In [51]:
embeddings2 = model.encode(sentences2, convert_to_tensor=True)
print(embeddings2)

tensor([[ 0.0163, -0.0700,  0.0384,  ...,  0.0447,  0.0254, -0.0023],
        [ 0.0054, -0.0920,  0.0140,  ...,  0.0167, -0.0086, -0.0424],
        [-0.0842, -0.0592, -0.0010,  ..., -0.0157,  0.0764,  0.0389]])


In [52]:
from sentence_transformers import util

In [53]:
cosine_scores = util.cos_sim(embeddings1, embeddings2)
print(cosine_scores)

tensor([[ 0.2838,  0.1310, -0.0029],
        [ 0.2277, -0.0327, -0.0136],
        [-0.0124, -0.0465,  0.6571]])


In [54]:
for i in range(len(sentences1)):
  for j in range(len(sentences2)):
    print('{} \t\t {} \t\t Score: {:.4f}'.format(sentences1[i], sentences2[j], cosine_scores[i][j]))

The cat sits outside 		 The dog plays in the garden 		 Score: 0.2838
The cat sits outside 		 A woman watches TV 		 Score: 0.1310
The cat sits outside 		 The new movie is so great 		 Score: -0.0029
A man is playing guitar 		 The dog plays in the garden 		 Score: 0.2277
A man is playing guitar 		 A woman watches TV 		 Score: -0.0327
A man is playing guitar 		 The new movie is so great 		 Score: -0.0136
The movies are awesome 		 The dog plays in the garden 		 Score: -0.0124
The movies are awesome 		 A woman watches TV 		 Score: -0.0465
The movies are awesome 		 The new movie is so great 		 Score: 0.6571


In [55]:
del model

In [56]:
gc.collect()

7

In [57]:
del util

In [58]:
gc.collect()

2239